services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ../project
    ports:
      - "8000:8000"
    volumes:
      - ../project:/app
    environment:
      DEBUG: "1"
      DJANGO_SETTINGS_MODULE: project.settings
    command: python manage.py runserver 0.0.0.0:8000