version: '3.8'

services:
  frontend:
    build: ./hottakers
    ports:
      - "5173:5173"
    volumes:
      - ./hottakers:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: ./project
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=project.settings
    command: python manage.py runserver 0.0.0.0:8000