# Generated by Django 5.1.5 on 2025-01-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
